tranql ingress api version upgrade
helx-charts/tranql-chart pull request #1
Opened 2021-09-16 19:34 UTC by muralikarthikk

2021-09-17 03:16 UTC, pj-linebaugh approved these changes

2021-09-17 19:03 UTC, cschreep requested changes
I notice this PR is directly into the main branch. @YaphetKG is this is a deliberate choice or have we just not set up a develop branch in this repo?

2021-09-20 12:26 UTC, YaphetKG commented
Hi @cschreep , Hi @muralikarthikk , it's just that we have not created develop yet. I have made that branch just now. @muralikarthikk , if you update PR to merge to develop that'd be awesome.

2021-09-20 14:53 UTC, muralikarthikk commented
Merge to develop.

2021-09-20 14:53 UTC, closed without merging